---
version: 2
dependencies:
  galaxy: requirements.yml
  python: requirements.txt

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest
  builder_image:
    name: quay.io/ansible/ansible-builder:latest
